# Generated by Django 3.1.3 on 2020-11-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
